### ISSUE TITLE
Silence console output if options.file is set

### ISSUE THREAD

**Issue by davetgreen** [leny/grunt-parker#3]
If we're choosing to output to file, we shouldn't see the results in the console. It's best to remove as much clutter from the console as possible.

I might have time this weekend to PR this, but I thought I'd raise it. :)

**Comment by leny** [comment]
Hi, thanks for your report!

Feel free to submit a PR when you have time, I will not be able to do it before long.

**Comment by leny** [comment]
Merged & published as `0.2.0`.
